# =============================================
# Demanda3D - Redis Image
# =============================================
FROM redis:8.0-alpine

LABEL org.demanda3d.service="redis-cache"
LABEL org.demanda3d.version="1.0"