# PostgreSQL Client Authentication Configuration
# TYPE  DATABASE    USER            ADDRESS                 METHOD

# Allow replication from slave container
local   replication all                                     trust
host    replication all             demanda-psql-rep-dev.demanda-net-dev  trust
host    replication all             0.0.0.0/0               md5

# Local connections
local   all         all                                     md5
host    all         all             127.0.0.1/32            md5
host    all         all             ::1/128                 md5

# Allow connections from application
host    all         all             0.0.0.0/0               md5